services:
  - type: web
    name: wedding-decor
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    region: frankfurt
    branch: master
    envVars:
      - key: DATABASE_URL
        value: postgresql://wedding_decor_db_user:X9S9rn1ZKDQJmHDfmtpg05EnH7MMelVS@dpg-d736krvgi27c73cuvnog-a/wedding_decor_db
      - key: NODE_ENV
        value: production
